In [ ]:
"""
DecodeLabs — Project 2: Data Classification Using AI

Goal:
Build a basic classification model using the Iris dataset.

Workflow:
1. Load and understand the dataset
2. Split data into training and testing sets
3. Scale the features
4. Train a K-Nearest Neighbors (KNN) classifier
5. Make predictions
6. Evaluate the model
7. Test the model with new data
"""

In [ ]:
# Pandas is used to load and work with the dataset
import pandas as pd

# NumPy is useful for working with numbers and arrays
import numpy as np

# Used to split the dataset into training and testing data
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Simple classification algorithm
from sklearn.neighbors import KNeighborsClassifier

# Used to check how accurate our model is
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [ ]:
#load dataset
from sklearn.datasets import load_iris
iris=load_iris()

In [ ]:

# Load the Iris dataset
iris = load_iris()

# Features and target values
X = iris.data
y = iris.target

# Dataset information
feature_names = iris.feature_names
class_names = iris.target_names

# Create a DataFrame for easier understanding
df = pd.DataFrame(X, columns=feature_names)

# Add flower species names
df["species"] = pd.Categorical.from_codes(y, class_names)



In [ ]:
print(df.head())

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa  


In [ ]:


print(f"\nTotal Samples: {df.shape[0]}")
print(f"Number of Features: {len(feature_names)}")
print(f"Number of Classes: {len(class_names)}")




Total Samples: 150
Number of Features: 4
Number of Classes: 3


In [ ]:
print("\nFeature Names:")
for feature in feature_names:
    print("-", feature)






Feature Names:
- sepal length (cm)
- sepal width (cm)
- petal length (cm)
- petal width (cm)


In [ ]:
print("\nClasses:")
for class_name in class_names:
    print("-", class_name)




Classes:
- setosa
- versicolor
- virginica


In [ ]:
print("\nFirst 5 Rows:")
print(df.head())




First 5 Rows:
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa  


In [ ]:
print("\nClass Distribution:")
print(df["species"].value_counts())




Class Distribution:
species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64


In [ ]:
print("\nBasic Statistics:")
print(df.describe())


Basic Statistics:
       sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  
count        150.000000  
mean           1.199333  
std            0.762238  
min            0.100000  
25%            0.300000  
50%            1.300000  
75%            1.800000  
max            2.500000  


,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa


In [ ]:
# ============================================================
# STEP 2 — Split the Dataset
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)


print(f"\nTraining Samples: {X_train.shape[0]}")
print(f"Testing Samples: {X_test.shape[0]}")


Training Samples: 120
Testing Samples: 30


In [ ]:
# ============================================================
# STEP 3 — Feature Scaling
# ============================================================

# Create the scaler
scaler = StandardScaler()

# Fit the scaler on training data and transform it
X_train_scaled = scaler.fit_transform(X_train)

# Transform testing data using the same scaler
X_test_scaled = scaler.transform(X_test)



print("\nFeature scaling completed successfully.")



Feature scaling completed successfully.


In [ ]:
# ============================================================
# STEP 4 — Build and Train the KNN Model
# ============================================================

# Create the KNN classifier
knn_model = KNeighborsClassifier(n_neighbors=5)

# Train the model
knn_model.fit(X_train_scaled, y_train)



print("\nKNN model trained successfully.")
print("Number of Neighbors (K): 5")


KNN model trained successfully.
Number of Neighbors (K): 5


In [ ]:
# ============================================================
# STEP 5 — Make Predictions
# ============================================================

# Predict flower classes for the test data
predictions = knn_model.predict(X_test_scaled)


# Display a few predictions
for actual, predicted in zip(y_test[:10], predictions[:10]):

    print(
        f"Actual: {class_names[actual]} | "
        f"Predicted: {class_names[predicted]}"
    )

Actual: setosa | Predicted: setosa
Actual: virginica | Predicted: virginica
Actual: versicolor | Predicted: versicolor
Actual: versicolor | Predicted: versicolor
Actual: setosa | Predicted: setosa
Actual: versicolor | Predicted: versicolor
Actual: setosa | Predicted: setosa
Actual: setosa | Predicted: setosa
Actual: virginica | Predicted: virginica
Actual: versicolor | Predicted: versicolor


In [ ]:
# ============================================================
# STEP 6 — Evaluate the Model
# ============================================================

# Calculate model accuracy
accuracy = accuracy_score(y_test, predictions)

# Create confusion matrix
cm = confusion_matrix(y_test, predictions)


print(f"\nModel Accuracy: {accuracy:.2%}")

print("\nConfusion Matrix:")
print(cm)

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        predictions,
        target_names=class_names
    )
)





Model Accuracy: 93.33%

Confusion Matrix:
[[10  0  0]
 [ 0 10  0]
 [ 0  2  8]]

Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       0.83      1.00      0.91        10
   virginica       1.00      0.80      0.89        10

    accuracy                           0.93        30
   macro avg       0.94      0.93      0.93        30
weighted avg       0.94      0.93      0.93        30



In [ ]:
# ============================================================
# STEP 7 — Predict a New Flower
# ============================================================

# New flower measurements
new_flower = np.array([
    [5.1, 3.5, 1.4, 0.2]
])

# Scale the new data
new_flower_scaled = scaler.transform(new_flower)

# Predict the flower species
new_prediction = knn_model.predict(new_flower_scaled)

predicted_species = class_names[new_prediction[0]]



print(f"\nNew Flower Features: {new_flower[0]}")
print(f"Predicted Species: {predicted_species}")

print("\nProject completed successfully.")


New Flower Features: [5.1 3.5 1.4 0.2]
Predicted Species: setosa

Project completed successfully.
